const materias = () => {
  return [
    {
      IngenieriaInformatica: {
        "Semestre 1": {
          "FUNDAMENTOS DE LA INFORMATICA": {
            codigo: "IC1222",
            nombre: "FUNDAMENTOS DE LA INFORMATICA",
            horasTeoricas: 0,
            horasPracticas: 2,
            horasSemanales: 2,
            uc: 3,
            prelaciones: "",
          },
          DEPORTE: {
            codigo: "DP0001",
            nombre: "DEPORTE",
            horasTeoricas: 0,
            horasPracticas: 2,
            horasSemanales: 2,
            uc: 2,
            prelaciones: "",
          },
          "MATEMATICA I": {
            codigo: "IM1421",
            nombre: "MATEMATICA I",
            horasTeoricas: 0,
            horasPracticas: 6,
            horasSemanales: 6,
            uc: 5,
            prelaciones: "",
          },
          "LOGICA MATEMATICA": {
            codigo: "IM1223",
            nombre: "LOGICA MATEMATICA",
            horasTeoricas: 0,
            horasPracticas: 5,
            horasSemanales: 5,
            uc: 3,
            prelaciones: "",
          },
          "FORMACION CONSTITUCIONAL": {
            codigo: "FC0001",
            nombre: "FORMACION CONSTITUCIONAL",
            horasTeoricas: 0,
            horasPracticas: 65,
            horasSemanales: 65,
            uc: 2,
            prelaciones: "",
          },
          "LENGUAJE Y COMUNICACION": {
            codigo: "IH1124",
            nombre: "LENGUAJE Y COMUNICACION",
            horasTeoricas: 0,
            horasPracticas: 3,
            horasSemanales: 3,
            uc: 2,
            prelaciones: "",
          },
          "INGLES I": {
            codigo: "IH1125",
            nombre: "INGLES I",
            horasTeoricas: 0,
            horasPracticas: 4,
            horasSemanales: 4,
            uc: 2,
            prelaciones: "",
          },
          "ECONOMIA DIGITAL": {
            codigo: "EC005",
            nombre: "ECONOMIA DIGITAL",
            horasTeoricas: 20,
            horasPracticas: 20,
            horasSemanales: 40,
            uc: 2,
            prelaciones: "",
          },
        },
        "Semestre 2": {
          "MATEMATICA II": {
            codigo: "IM2421",
            nombre: "MATEMATICA II",
            horasTeoricas: 0,
            horasPracticas: 11,
            horasSemanales: 11,
            uc: 5,
            prelaciones: "MATEMATICA I",
          },
          "PROBLEMATICA CIENTIFICA TECNOL": {
            codigo: "IH2124",
            nombre: "PROBLEMATICA CIENTIFICA TECNOL",
            horasTeoricas: 0,
            horasPracticas: 9,
            horasSemanales: 9,
            uc: 2,
            prelaciones: "13 U.C Aprobadas",
          },
          "FISICA I": {
            codigo: "IB2322",
            nombre: "FISICA I",
            horasTeoricas: 0,
            horasPracticas: 7,
            horasSemanales: 7,
            uc: 4,
            prelaciones: "MATEMATICA I",
          },
          "ELECTIVA I (CONDUCTA HUMANA)": {
            codigo: "IME320",
            nombre: "ELECTIVA I (CONDUCTA HUMANA)",
            horasTeoricas: 0,
            horasPracticas: 55,
            horasSemanales: 55,
            uc: 2,
            prelaciones: "13 U.C Aprobadas",
          },
          "ALGORITMOS I": {
            codigo: "IC2323",
            nombre: "ALGORITMOS I",
            horasTeoricas: 0,
            horasPracticas: 8,
            horasSemanales: 8,
            uc: 3,
            prelaciones: "LOGICA MATEMATICA",
          },
          "ARTE Y CULTURA": {
            codigo: "AC0001",
            nombre: "ARTE Y CULTURA",
            horasTeoricas: 0,
            horasPracticas: 2,
            horasSemanales: 2,
            uc: 2,
            prelaciones: "FORMACION CONSTITUCIONAL",
          },
          "INGLES II": {
            codigo: "IH2125",
            nombre: "INGLES II",
            horasTeoricas: 0,
            horasPracticas: 10,
            horasSemanales: 10,
            uc: 2,
            prelaciones: "INGLES I",
          },
        },
        "Semestre 3": {
          "ALGORITMOS II": {
            codigo: "IC3323",
            nombre: "ALGORITMOS II",
            horasTeoricas: 0,
            horasPracticas: 14,
            horasSemanales: 14,
            uc: 3,
            prelaciones: "ALGORITMOS I",
          },
          "ELECTIVA II (LEGISLACION INFOR)": {
            codigo: "IME520",
            nombre: "ELECTIVA II (LEGISLACION INFOR)",
            horasTeoricas: 0,
            horasPracticas: 57,
            horasSemanales: 57,
            uc: 2,
            prelaciones: "ELECTIVA I (CONDUCTA HUMANA)",
          },
          "PROGRAMACION I": {
            codigo: "IC3244",
            nombre: "PROGRAMACION I",
            horasTeoricas: 0,
            horasPracticas: 13,
            horasSemanales: 13,
            uc: 4,
            prelaciones: "ALGORITMOS I",
          },
          "MATEMATICA III": {
            codigo: "IM3421",
            nombre: "MATEMATICA III",
            horasTeoricas: 0,
            horasPracticas: 16,
            horasSemanales: 16,
            uc: 5,
            prelaciones: "MATEMATICA II",
          },
          "FISICA II": {
            codigo: "IB3322",
            nombre: "FISICA II",
            horasTeoricas: 0,
            horasPracticas: 12,
            horasSemanales: 12,
            uc: 4,
            prelaciones: "FISICA I",
          },
          "METODOLOGIA Y TECNICAS DE INVE": {
            codigo: "IH3125",
            nombre: "METODOLOGIA Y TECNICAS DE INVE",
            horasTeoricas: 0,
            horasPracticas: 15,
            horasSemanales: 15,
            uc: 2,
            prelaciones: "30 U.C Aprobadas",
          },
        },
        "Semestre 4": {
          "PROBABILIDADES Y ESTADISTICA": {
            codigo: "IM5421",
            nombre: "PROBABILIDADES Y ESTADISTICA",
            horasTeoricas: 0,
            horasPracticas: 20,
            horasSemanales: 20,
            uc: 3,
            prelaciones: "MATEMATICA III",
          },
          "MATEMATICA IV": {
            codigo: "IM4421",
            nombre: "MATEMATICA IV",
            horasTeoricas: 0,
            horasPracticas: 19,
            horasSemanales: 19,
            uc: 5,
            prelaciones: "MATEMATICA III",
          },
          "PROGRAMACION II": {
            codigo: "IC4244",
            nombre: "PROGRAMACION II",
            horasTeoricas: 0,
            horasPracticas: 17,
            horasSemanales: 17,
            uc: 4,
            prelaciones: "PROGRAMACION I",
          },
          "ELECTIVA III (MANTENIMIENTO DEL COMPUTADOR)": {
            codigo: "IME720",
            nombre: "ELECTIVA III (MANTENIMIENTO DEL COMPUTADOR)",
            horasTeoricas: 0,
            horasPracticas: 21,
            horasSemanales: 21,
            uc: 2,
            prelaciones: "ELECTIVA II (LEGISLACION INFOR)",
          },
          "ESTRUCTURAS DISCRETAS I": {
            codigo: "IM4323",
            nombre: "ESTRUCTURAS DISCRETAS I",
            horasTeoricas: 0,
            horasPracticas: 18,
            horasSemanales: 18,
            uc: 4,
            prelaciones: "ALGORITMOS II",
          },
          "BASE DE DATOS": {
            codigo: "IS4225",
            nombre: "BASE DE DATOS",
            horasTeoricas: 0,
            horasPracticas: 22,
            horasSemanales: 22,
            uc: 3,
            prelaciones: "PROGRAMACION I",
          },
        },
        "Semestre 5": {
          "TEORIA DE SISTEMAS": {
            codigo: "IS5205",
            nombre: "TEORIA DE SISTEMAS",
            horasTeoricas: 0,
            horasPracticas: 28,
            horasSemanales: 28,
            uc: 2,
            prelaciones: "50 U.C Aprobadas",
          },
          "ALGEBRA BOOLEANA": {
            codigo: "IM5221",
            nombre: "ALGEBRA BOOLEANA",
            horasTeoricas: 0,
            horasPracticas: 25,
            horasSemanales: 25,
            uc: 3,
            prelaciones: "ESTRUCTURAS DISCRETAS I",
          },
          "ESTRUCTURAS DISCRETAS II": {
            codigo: "IM5323",
            nombre: "ESTRUCTURAS DISCRETAS II",
            horasTeoricas: 0,
            horasPracticas: 26,
            horasSemanales: 26,
            uc: 4,
            prelaciones: "ESTRUCTURAS DISCRETAS I",
          },
          "PROGRAMACION III": {
            codigo: "IC5244",
            nombre: "PROGRAMACION III",
            horasTeoricas: 0,
            horasPracticas: 23,
            horasSemanales: 23,
            uc: 4,
            prelaciones: "PROGRAMACION II",
          },
          "ELECTIVA IV (TELEINFORMATICA)": {
            codigo: "IMEIV",
            nombre: "ELECTIVA IV (TELEINFORMATICA)",
            horasTeoricas: 0,
            horasPracticas: 27,
            horasSemanales: 27,
            uc: 2,
            prelaciones: "ELECTIVA III (MANTENIMIENTO DEL COMPUTADOR)",
          },
          "ORGANIZACION DEL COMPUTADOR": {
            codigo: "IC5422",
            nombre: "ORGANIZACION DEL COMPUTADOR",
            horasTeoricas: 0,
            horasPracticas: 24,
            horasSemanales: 24,
            uc: 5,
            prelaciones: "FISICA II",
          },
        },
        "Semestre 6": {
          "INVESTIGACION DE OPERACIONES": {
            codigo: "ID6241",
            nombre: "INVESTIGACION DE OPERACIONES",
            horasTeoricas: 0,
            horasPracticas: 31,
            horasSemanales: 31,
            uc: 4,
            prelaciones: "(249) PROBABILIDADES Y ESTADISTICA",
          },
          "ARQUITECTURA DEL COMPUTADOR": {
            codigo: "IC6322",
            nombre: "ARQUITECTURA DEL COMPUTADOR",
            horasTeoricas: 0,
            horasPracticas: 29,
            horasSemanales: 29,
            uc: 4,
            prelaciones: "(631) ORGANIZACION DEL COMPUTADOR",
          },
          "SISTEMAS DE INFORMACION I": {
            codigo: "IS6425",
            nombre: "SISTEMAS DE INFORMACION I",
            horasTeoricas: 0,
            horasPracticas: 33,
            horasSemanales: 33,
            uc: 5,
            prelaciones: "(180) TEORIA DE SISTEMAS",
          },
          "METODOS NUMERICOS": {
            codigo: "IM6243",
            nombre: "METODOS NUMERICOS",
            horasTeoricas: 0,
            horasPracticas: 32,
            horasSemanales: 32,
            uc: 4,
            prelaciones: "(827) ESTRUCTURAS DISCRETAS II",
          },
          "INGENIERIA ECONOMICA": {
            codigo: "ID6124",
            nombre: "INGENIERIA ECONOMICA",
            horasTeoricas: 0,
            horasPracticas: 30,
            horasSemanales: 30,
            uc: 2,
            prelaciones: "70 U.C Aprobadas",
          },
          "ELECTIVA V": {
            codigo: "IMEV",
            nombre: "ELECTIVA V",
            horasTeoricas: 0,
            horasPracticas: 59,
            horasSemanales: 59,
            uc: 2,
            prelaciones: "(125) ELECTIVA IV (TELEINFORMATICA)",
          },
        },
        "Semestre 7": {
          "ORGANIZACION Y GESTION EMPRESA": {
            codigo: "ID7323",
            nombre: "ORGANIZACION Y GESTION EMPRESA",
            horasTeoricas: 0,
            horasPracticas: 36,
            horasSemanales: 36,
            uc: 4,
            prelaciones: "86 U.C Aprobadas",
          },
          "TRADUCTORES E INTERPRETES": {
            codigo: "IS7244",
            nombre: "TRADUCTORES E INTERPRETES",
            horasTeoricas: 0,
            horasPracticas: 37,
            horasSemanales: 37,
            uc: 4,
            prelaciones: "(827) ESTRUCTURAS DISCRETAS II",
          },
          "SISTEMAS OPERATIVOS": {
            codigo: "IC7322",
            nombre: "SISTEMAS OPERATIVOS",
            horasTeoricas: 0,
            horasPracticas: 34,
            horasSemanales: 34,
            uc: 4,
            prelaciones: "(17) ARQUITECTURA DEL COMPUTADOR",
          },
          "SISTEMAS DE INFORMACION II": {
            codigo: "IS7324",
            nombre: "SISTEMAS DE INFORMACION II",
            horasTeoricas: 0,
            horasPracticas: 38,
            horasSemanales: 38,
            uc: 5,
            prelaciones: "(299) SISTEMAS DE INFORMACION I",
          },
          "CONTROL DE PROYECTOS": {
            codigo: "ID7322",
            nombre: "CONTROL DE PROYECTOS",
            horasTeoricas: 0,
            horasPracticas: 35,
            horasSemanales: 35,
            uc: 4,
            prelaciones: "86 U.C Aprobadas",
          },
        },
        "Semestre 8": {
          "ELECTIVA DE AREA I": {
            codigo: "EA",
            nombre: "ELECTIVA DE AREA I",
            horasTeoricas: 0,
            horasPracticas: 39,
            horasSemanales: 39,
            uc: 4,
            prelaciones: "100 U.C Aprobadas",
          },
          PASANTIA: {
            codigo: "ID8082",
            nombre: "PASANTIA",
            horasTeoricas: 0,
            horasPracticas: 40,
            horasSemanales: 40,
            uc: 4,
            prelaciones: "(267) CONTROL DE PROYECTOS",
          },
          "LENGUAJE DE PROGRAMACION": {
            codigo: "IS8243",
            nombre: "LENGUAJE DE PROGRAMACION",
            horasTeoricas: 0,
            horasPracticas: 41,
            horasSemanales: 41,
            uc: 4,
            prelaciones: "(283) TRADUCTORES E INTERPRETES",
          },
          "SISTEMAS DE INFORMACION III": {
            codigo: "IS8424",
            nombre: "SISTEMAS DE INFORMACION III",
            horasTeoricas: 0,
            horasPracticas: 42,
            horasSemanales: 42,
            uc: 5,
            prelaciones: "(755) SISTEMAS DE INFORMACION II",
          },
          REDES: {
            codigo: "IT8241",
            nombre: "REDES",
            horasTeoricas: 0,
            horasPracticas: 43,
            horasSemanales: 43,
            uc: 4,
            prelaciones: "(313) SISTEMAS OPERATIVOS",
          },
        },
        "Semestre 9": {
          "ELECTIVA LIBRE I": {
            codigo: "EL9325",
            nombre: "ELECTIVA LIBRE I",
            horasTeoricas: 0,
            horasPracticas: 1,
            horasSemanales: 1,
            uc: 4,
            prelaciones: "136 U.C Aprobadas",
          },
          "SISTEMAS DISTRIBUIDOS": {
            codigo: "IT9241",
            nombre: "SISTEMAS DISTRIBUIDOS",
            horasTeoricas: 0,
            horasPracticas: 46,
            horasSemanales: 46,
            uc: 4,
            prelaciones: "(165) REDES",
          },
          "ELECTIVA DE AREA II": {
            codigo: "EA9244",
            nombre: "ELECTIVA DE AREA II",
            horasTeoricas: 0,
            horasPracticas: 44,
            horasSemanales: 44,
            uc: 4,
            prelaciones: "(60) ELECTIVA DE AREA I",
          },
          "ETICA PROFESIONAL": {
            codigo: "IH9202",
            nombre: "ETICA PROFESIONAL",
            horasTeoricas: 0,
            horasPracticas: 45,
            horasSemanales: 45,
            uc: 2,
            prelaciones: "(755) SISTEMAS DE INFORMACION II",
          },
          "PROYECTO DE GRADO I": {
            codigo: "PG9083",
            nombre: "PROYECTO DE GRADO I",
            horasTeoricas: 0,
            horasPracticas: 47,
            horasSemanales: 47,
            uc: 4,
            prelaciones: "157 U.C Aprobadas",
          },
        },
        "Semestre 10": {
          "ELECTIVA DE AREA III": {
            codigo: "EA0244",
            nombre: "ELECTIVA DE AREA III",
            horasTeoricas: 0,
            horasPracticas: 48,
            horasSemanales: 48,
            uc: 4,
            prelaciones: "(549) ELECTIVA DE AREA II",
          },
          "ELECTIVA LIBRE II": {
            codigo: "EL",
            nombre: "ELECTIVA LIBRE II",
            horasTeoricas: 0,
            horasPracticas: 49,
            horasSemanales: 49,
            uc: 3,
            prelaciones: "157 U.C Aprobadas",
          },
          "PROYECTO DE GRADO II": {
            codigo: "PG0083",
            nombre: "PROYECTO DE GRADO II",
            horasTeoricas: 0,
            horasPracticas: 52,
            horasSemanales: 52,
            uc: 4,
            prelaciones: "(103) PROYECTO DE GRADO I",
          },
          "INFORMATICA EDUCATIVA": {
            codigo: "IS0222",
            nombre: "INFORMATICA EDUCATIVA",
            horasTeoricas: 0,
            horasPracticas: 51,
            horasSemanales: 51,
            uc: 3,
            prelaciones: "157 U.C Aprobadas",
          },
          "GERENCIA DE PROYECTO": {
            codigo: "ID0221",
            nombre: "GERENCIA DE PROYECTO",
            horasTeoricas: 0,
            horasPracticas: 50,
            horasSemanales: 50,
            uc: 3,
            prelaciones: "(435) PASANTIA",
          },
        },
      },
    },
  ];
};

export default materias;
